spring:
  datasource:
    url: jdbc:postgresql://m1-db:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0  # random port for dynamic assignment

kartim:
  billing:
    durations:
      - minutes: 10
        price: 15000
      - minutes: 15
        price: 50000
      - minutes: 20
        price: 25000
