spring:
  datasource:
    url: jdbc:postgresql://m1-db:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0  # random port for dynamic assignment

config:
  duration:
    preReservationTime: 10
    postReservationTime: 10
  tax: 0.19
  pricing:
    10: 15000
    15: 20000
    20: 25000
