server:
  port: 8761

spring:
  application:
    name: net-eureka

eureka:
  client:
    service-url:
      defaultZone: http://net-eureka:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
